version: "3.8"

services:
  testdb:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: test_snippets_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data_test

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: snippets_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
      - testdb
    ports:
      - "3000:3000"
    # The CMD in Dockerfile runs tests and then starts the server
    restart: "no" # Set to "on-failure" or "always" for production

  web:
    build:
      context: ./ui
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      VITE_API_BASE_URL: http://api:3000
      PORT: 3030
    ports:
      - "3030:3030"
    depends_on:
      - api
    restart: "no"

volumes:
  pgdata:
